### ISSUE TITLE
Add example to readme

### ISSUE THREAD

**Issue by fiammybe** [imponeer/extension-info-contracts#15]
It would be very helpful to show how to use this module with a few examples.

**Comment by MekDrop** [comment]
Not a real example but I added section for implementations into Readme, because it's hard to give something for such big library.

For now I'm working for making implementation for dealing with @ImpressCMS modules and themes. Once that will work ir will be possible easy to describe other extension like for @Xoops or/and @XoopsCube or any non xoops-like CMS like @Wordpress. So, theoretically (in reality somebody will need to make bridges for that) if CMS will support this contract will be possible to install modules made for another.
